name = input("Enter name: ").strip().title()
email = input("Enter email: ").strip().lower()
country = input("Enter country: ").strip().upper()
username, domain = email.split("@")
x = len(name.split())
print("\n\n ------user profile------\n")
print(f"{'Name':<13}: {name}")
print(f"{'Email':<13}: {email}")
print(f"{'Country':<13}: {country}")
print(f"{'Username':<13}: {username}")
print(f"{'Mail Domain':<13}: {domain}")
print(f"{'Name parts':<13}: {x}")